from pathlib import Path
import joblib
import numpy as np
import warnings

warnings.filterwarnings(
    "ignore",
    message="X does not have valid feature names.*"
)

LABEL_MAP = {
    0: "vegetable",
    1: "fruit"
}

MODEL_PATH = Path(__file__).resolve().parent / "svm_pipeline.joblib"

# Load the trained model only once when this file is imported
model = joblib.load(MODEL_PATH)


def predict(feature_vector):
    """
    Predict the class label for one preprocessed feature vector.

    Input:
        feature_vector: numeric feature vector generated by the provided preprocess code

    Output:
        A string: "fruit" or "vegetable"
    """

    x = np.asarray(feature_vector, dtype=np.float32)

    if x.ndim == 1:
        x = x.reshape(1, -1)

    pred = model.predict(x)[0]

    try:
        return LABEL_MAP[int(pred)]
    except (ValueError, TypeError, KeyError):
        return str(pred)